name: bimbeer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.5.2
  equatable: ^2.0.5
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^5.0.8
  flutter_geo_hash: ^0.0.4
  formz: ^0.6.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  http: ^0.13.5
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+4
  numberpicker: ^2.1.2
  rxdart: ^0.27.7
  step_progress_indicator: ^1.0.2
  swipe_cards: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/fonts/Pacifico/
    - assets/fonts/Poppins/
