name: bimbeer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <3.13.0"

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.5.2
  equatable: ^2.0.5
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^6.0.2
  flutter_geo_hash: ^0.0.4
  flutter_launcher_icons: ^0.13.1
  formz: ^0.6.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.0
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  numberpicker: ^2.1.2
  rxdart: ^0.27.7
  step_progress_indicator: ^1.0.2
  swipe_cards: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/fonts/Pacifico/
    - assets/fonts/Poppins/

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/beer-android-icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_android: "#000000"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
